name: Build and Push kuberhealthy check images
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ministryofjustice/cloud-platform-kuberhealthy-namespace-check
          tags: |
             type=ref,event=tag

      - name: Build and push to docker hub
        uses: docker/build-push-action@v3
        with:
          context: cmd/namespace-check
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}
  