name: Build and Push to docker on PR 
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  push_to_ecr:
    name: Push image to ECR
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        uses: docker/build-push-action@v3
        env:
          REPOSITORY: webops/cloud-platform-kuberhealthy-checks
        with:
          context: .
          file: cmd/namespace-check/Dockerfile        
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ github.sha }}