name: Build and Push kuberhealthy check image on PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  push_to_ecr:
    name: Push image to ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@2fc7aceee09e9e4a7105c0d060c656fad0b4f63d # v1.7.0

      - name: Build, tag, and push docker image to Amazon ECR
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        env:
          REPOSITORY: webops/cloud-platform-kuberhealthy-checks
          IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
        with:
          context: .
          file: cmd/namespace-check/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}