name: staticcheck
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Install Go on the VM running the action.
      - uses: WillAbides/setup-go-faster@8af5eb44e6d2676b48dfd4730ee3902f41d59584 # v1.7.0
        with:
          go-version: "1.21.x"

      - name: Perform staticcheck on codebase
        uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 # v1.3.1
        with:
          install-go: false

      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt command
        run: |
          gofumpt -l -w ./

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
