name: Build, push and test docker image
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ministryofjustice/cloud-platform-kuberhealthy-namespace-check
          tags: |
            type=ref,event=branch

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: cmd/namespace-check
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

  